### ISSUE TITLE
Error "   batch_size = layer_dict['batch'] KeyError: 'batch'"

### ISSUE THREAD

**Issue by ggzzzzz628** [zombie0117/yolov3-tiny-onnx-TensorRT#13]
Traceback (most recent call last):
  File "yolov3_to_onnx.py", line 834, in <module>
    main()
  File "yolov3_to_onnx.py", line 822, in main
    verbose=True)
  File "yolov3_to_onnx.py", line 423, in build_onnx_graph
    major_node_specs = self._make_onnx_node(layer_name, layer_dict)
  File "yolov3_to_onnx.py", line 477, in _make_onnx_node
    layer_name, layer_dict)
  File "yolov3_to_onnx.py", line 510, in _make_input_tensor
    batch_size = layer_dict['batch']
KeyError: 'batch'

How to solve

**Comment by AwosomeTony** [comment]
Hello, did you solve this problem? I met the same issue.
