### ISSUE TITLE
engine = builder.build_cuda_engine(network)             engine 为None

### ISSUE THREAD

**Issue by yinqs** [zombie0117/yolov3-tiny-onnx-TensorRT#16]

**Comment by zhui-ying** [comment]
I have the same question
`Completed creating Engine
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 228, in <module>
    main()
  File "onnx_to_tensorrt.py", line 186, in main
    with get_engine(onnx_file_path, batch_size, fp16_on, engine_file_path) as engine, engine.create_execution_context() as context:
  File "onnx_to_tensorrt.py", line 127, in get_engine
    return build_engine()
  File "onnx_to_tensorrt.py", line 118, in build_engine
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'`

**Comment by zhui-ying** [comment]
I have the same question
`Completed creating Engine  
Traceback (most recent call last):  
  File "onnx_to_tensorrt.py", line 228, in <module>  
    main()  
  File "onnx_to_tensorrt.py", line 186, in main  
    with get_engine(onnx_file_path, batch_size, fp16_on, engine_file_path) as engine,  
 engine.create_execution_context() as context:
  File "onnx_to_tensorrt.py", line 127, in get_engine
    return build_engine()  
  File "onnx_to_tensorrt.py", line 118, in build_engine  
    f.write(engine.serialize())  
AttributeError: 'NoneType' object has no attribute 'serialize' `
